import { Comfortaa, Geist, Geist_Mono, Manrope, Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Suspense } from "react";
import AnimatedLoader from "@/components/custom/animatedLogo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "500", "400", "600", "700"], // add more weights if needed
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${comfortaa.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
      >
        <Suspense fallback={<AnimatedLoader />}>
          <Toaster position="top-right" />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
